extends Node
##In essence, the file managers purpose is to make sure that the right files are saved and managed proplery
## NOTE: Something to keep in mind is that static things should be stored in the res:// directory and things like save data
## and user history should be stored in user://


#region Variables
#Establishes a reference to the player save data
const save_directory = "user://Player Data/Saves/"
#Save data file path
var save_data_file_path: String = "user://Player Data/Saves/save_data.json"
#References the temporary data folder which contain most generated resources
const temporary_directory = "user://Player Data/Temporary Data/"
#Meant to refernce the history file generated by the player
var history_file = temporary_directory + "history.json"
#Default values for the save data file
var save_data_default = {
	"Scene Info": [],          # List of scene dictionaries
	"Object Info": [],         # List of objects
	"Player Info": [],         # List of players
	"Dialogue Info": []        # List of dialogue states
}
#Regex meant to catch floats inside of a string
var regex: RegEx
	#region Requested Save Data
#Holds the rquested dialogue data for the save function
var scene_data: Array = []
var object_data: Array = []
var player_data: Array = []
var dialogue_data: Array = []
	#endregion Requested Save Data
#endregion Variables


## Makes sure that the necesary folders are there and if not makes them.
func _ready() -> void:
	#Ensures that the temporary data folder is there
	var user_directory = DirAccess.open("user://")
	var relative_path_temporary_data = temporary_directory.get_base_dir().trim_prefix("user://")
	var relative_path_save_directory = save_directory.get_base_dir().trim_prefix("user://")
	
	#Checks if the temporary_directory exists and if not, makes it.
	if not user_directory.dir_exists(relative_path_temporary_data):
		var new_directory = user_directory.make_dir_recursive(relative_path_temporary_data)
		if new_directory != OK:
			push_error("Failed to find path or create Temporary Data Folder")
	#Checks if the save_directory exists and if not, makes it.
	if not user_directory.dir_exists(relative_path_save_directory):
		var new_directory = user_directory.make_dir_recursive(relative_path_save_directory)
		if new_directory != OK:
			push_error("Failed to find path or create Temporary Data Folder")
	#Regex initialization 
	regex = RegEx.new()
	regex.compile(r"-?\d+(\.\d+)?")
	#Connects the recieve_save_data function to the emissions of save info so that it can record the save information from relevent parties
	autoload_script_signal_manager.connect("send_save_info", receive_save_data)


## Contains the functions used to save and help save the game
#region Save Game Functionality
## Saves the game
func save_game(save_name: String) -> void:
	var save_path = save_directory.path_join(save_name)
	print("Save Directory: ", save_path)
	#region Save Folder Management
	#Checks to confirm if the save directory itself is detected
	if not DirAccess.dir_exists_absolute(save_directory):
		push_error("Save directory not found at: ", save_directory)
		return
	#Checks for duplicates, and if there are, overwrites them
	if DirAccess.dir_exists_absolute(save_path):
		var overwrite_dir = DirAccess.open(save_path)
		#Starts a stream that allows you to use .get_next() to itterate through the whole file list
		overwrite_dir.list_dir_begin()
		#Isolates the name of the file
		var file = overwrite_dir.get_next()
		while file != "":
			if not overwrite_dir.current_is_dir():
				overwrite_dir.remove(file)
			file = overwrite_dir.get_next()
		#Closes the directory stream to ensure it is closed
		overwrite_dir.list_dir_end()
		print("Overwrite Complete, files in: ", save_path, " deleted.")
	#Checks to see if the folder was created, and if not, it pushes an error
	else:
		var save_folder = DirAccess.make_dir_absolute(save_path)
		if save_folder == OK:
			print("Save folder: ", save_name, " created at: ", save_path)
		else:
			push_error("Failed to create save folder: ", save_path)
	#After the code clears this segment, it starts saving files to the designated folder
	#Code that copies and saves the history files
	#endregion Save Folder Management
	#region Save File Creation and Management
		#region Save Date & Time
	#Grabs the system time and date and mashes them together in a string
	var date: String = Time.get_date_string_from_system(false)
	var time: String = Time.get_time_string_from_system(false)
	var date_time: String = date + " " + time
	#Save ID - Creates a config file that stores the creation date of the save using system time
	var save_id = ConfigFile.new()
	save_id.set_value("Save ID Values", "Save Date", date_time)
	var path_save_id = save_directory.path_join(save_name).path_join("save_id.cfg")
	save_id.save(path_save_id)
		#endregion Save Date & Time
		
		#region Game Environment
	#Empties out the old values and sends out a request to all connected scripts to send their save data
	scene_data = []
	player_data = []
	object_data = []
	dialogue_data = []
	#Scene Data collection
	var dictionary_active_scenes = autoload_script_scene_manager.dictionary_active_scenes
	for scene in dictionary_active_scenes: 
		var scene_dictionary = {
			"Scene Name": scene,
			"Scene Path": dictionary_active_scenes[scene]["path"],
			"Current Canvas Layer": dictionary_active_scenes[scene]["canvas"].layer,
			"Current Visibility": dictionary_active_scenes[scene]["visibility"]
		}
		scene_data.append(scene_dictionary)
	#Requests save information from the other scripts
	autoload_script_signal_manager.emit_signal("request_save_info")
	var save_data_final = save_data_default.duplicate(true)
	save_data_final["Scene Info"] = scene_data
	save_data_final["Player Info"] = player_data
	save_data_final["Object Info"] = object_data
	save_data_final["Dialogue Info"] = dialogue_data
	#gets all children of the game_environment and checks if they are in the scene_level group
	var save_file_path = save_path.path_join("save_data.json")
	var save_data_file = FileAccess.open(save_file_path, FileAccess.WRITE)
	if save_data_file:
		save_data_file.store_string(JSON.stringify(save_data_final, "\t", 0))
		save_data_file.close()
	else:
		push_error("script_save_manager save_data_file failed to be created")
		#endregion Gamer Environment

		#region History
	var path_copy_destination = save_directory.path_join(save_name).path_join("history.json")
	if DirAccess.copy_absolute(history_file, path_copy_destination) !=OK:
		push_error("Failed to copy: ", history_file, "\nDestination: ", path_copy_destination)


## Recieves the dialogue save info and writes it to the dictionary
func receive_save_data(save_data_dictionary: Dictionary, signal_origin) -> void:
	match signal_origin:
		"player":
			for data in save_data_dictionary:
				player_data.append(save_data_dictionary[data])
			print("script_save_manager player_data merged with received data")
		"object":
			for data in save_data_dictionary:
				object_data.append(save_data_dictionary[data])
			print("script_save_manager object_data merged with received data")
		"dialogue":
			for data in save_data_dictionary:
				dialogue_data.append(save_data_dictionary[data])
			print("script_save_manager dialogue_data merged with received data")
		_:
			push_error("script_save_manager function receive_save_data has received an unrecognized dictionary")
	#endregion Save File Creation and Management


## Deletes save folders
func save_delete(save_name: String) -> void:
	var save_path = save_directory.path_join(save_name)
	#Since folders cannot be deleted with stuff inside of them, the for loop finds and 
	#deletes all items (not folders) inside of the save path before removing the folder. 
	if DirAccess.dir_exists_absolute(save_path):
		for file_name in DirAccess.get_files_at(save_path):
			var file_path = save_path.path_join(file_name)
			DirAccess.remove_absolute(file_path)
		DirAccess.remove_absolute(save_path)
		print("Save: ", save_name, " deleted at path: ", save_path)
	else:
		push_error("script_save_manager -> save_delete to determine save_path")
	#Final safty check to see if it fully deleted
	if DirAccess.dir_exists_absolute(save_path):
		push_error("script_save_manager -> save_delete failed to delete save folder")
#endregion Save Game Functionality


#region Checks
## Checks to see if the folder name is valid
func check_valid_folder_name(folder_name: String) -> bool:
	#This code returns true if the input string is a valid folder name
	#First checks if the string is empty
	if folder_name.is_empty() or folder_name.strip_edges().is_empty():
		return false
	
	# Windows folders that are invalid
	var win_reserved_names = [
		"CON", "PRN", "AUX", "NUL",
		"COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
		"LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"
	]
	if win_reserved_names.has(folder_name.to_upper()):
		return false
	
	# Characters invalid on both Windows and Linux
	var invalid_characters  = ['/', '\\', '<', '>', ':', '"', '|', '?', '*']
	for characters in invalid_characters :
		if folder_name.contains(characters ):
			return false
	
	#Checks for spaces and . at the begning and ends of folder names
	if folder_name.begins_with(".") or folder_name.ends_with(".") or \
		folder_name.begins_with(" ") or folder_name.ends_with(" "):
		return false    
	
	#Checks the folder length and returns true if it is below the length
	return folder_name.length() <= 255


## Checks to see if there is a duplicate save folder
func check_save_duplicate(save_name: String) -> bool:
	#Returns false if ther isn't a duplicate folder
	var save_path = save_directory+save_name
	print("Save Directory: ", save_path)
	#Checks to confirm if the save directory itself is detected
	if not DirAccess.dir_exists_absolute(save_directory):
		push_error("Save directory not found at: ", save_directory)
		return true
	#Checks to see if the a folder with the same name as the save_name exists
	if DirAccess.dir_exists_absolute(save_path):
		print("Save folder already exists")
		return true
	#If it can't find a duplicate
	return false
#endregion Checks


func _on_button_pressed() -> void:
	pass # Replace with function body.
#endregion Save Game Functionality


#Contains the functions meant to load and help load the game
#region Load Game Functionality
## Meant to load a save from a save folder
func load_game(save_name: String) -> void:
	var save_path = save_directory+save_name
	print("Save Directory: ", save_path)
	#Checks to see if directories exists before proceeding
	#region Directory Checks
	#Checks to see if the save_directory exists
	if not DirAccess.dir_exists_absolute(save_directory):
		push_error("Save directory not found at: ", save_directory)
		return 
	#Checks to see if the save_path exists
	if not DirAccess.dir_exists_absolute(save_path):
		push_error("Save path not found at: ", save_path)
		return 
	#endregion Directory Checks
	
	#Responsible for retreving the save data from the save_data.json in the save folder
	#region Data Retrieval 
	#Retrieves the save data as text
	var save_data
	var save_file = FileAccess.open(save_path.path_join("save_data.json"), FileAccess.READ)
	var save_file_text = save_file.get_as_text()
	save_file.close()
	#Converts the text data to json data and the json data to a save_data dictionary
	var json = JSON.new()
	var json_check = json.parse(save_file_text)
	if json_check == OK:
		save_data = json.data
		if typeof(save_data) == TYPE_DICTIONARY:
			print(save_data)
		else:
			push_error("Unexpected data type when loading save_data from: ", save_name)
			return
	else:
		push_error("JSON data failed to load in script_save_manager")
		return
	#endregion Data Retrieval
	
	#Loads the scenes and removes the old ones
	#region Scene Managment
	if save_data["Scene Info"].is_empty() != true:
		#Removes all scenes
		await autoload_script_scene_manager.scene_remove_all()
		var scene_info = save_data["Scene Info"]
		for scene in scene_info:
			print("Loading: ", scene["Scene Name"], " from: ", scene["Scene Path"])
			autoload_script_scene_manager.scene_load(scene["Scene Name"], scene["Scene Path"])
			#moves the loaded scene to the appropriate layer
			autoload_script_scene_manager.scene_layer_move(scene["Scene Name"], scene["Current Canvas Layer"])
			#adjusts visibility based on save data
			if scene["Current Visibility"] == true:
				autoload_script_scene_manager.scene_show(scene["Scene Name"])
			else:
				autoload_script_scene_manager.scene_hide(scene["Scene Name"])
		#Hides the escape menu if it was visible in the save since it can be visible when the player is saving. 
		autoload_script_scene_manager.scene_hide("scene_escape_menu")
	#endregion Scene Managment
	
	#Itterates over the objects in the save file and assigns the correct states
	#region Object Managment
	if save_data["Object Info"].is_empty() != true:
	#Objects in the scene are put into a dictionary as it is faster to search over that to find our values
		var interactable_objects = get_tree().get_nodes_in_group("interactables")
		var dictionary_interactable_objects = {}
		for node in interactable_objects:
			dictionary_interactable_objects[node.object_id] = node
		#For each object in the save data file, find the object in the scene and copy over the data
		for object in save_data["Object Info"]:
			if object["Object ID"] in dictionary_interactable_objects:
				var current_object = dictionary_interactable_objects[object["Object ID"]] 
				current_object.object_interaction_type = int(object["Object Interaction Type"])
				current_object.is_interactable = bool(object["Object is Interactable"])
				current_object.current_dialogue_segment = object["Current Dialogue Segment"]
	#endregion Object Managment
	
	#Itterates over the player dictionary to find the active player
	#region Player Managment
	#Finds and adds all members of the player group to a dictionary for faster referencing
	if save_data["Player Info"].is_empty() != true:
		var player_objects = get_tree().get_nodes_in_group("player")
		var dictionary_player_objects = {}
		for node in player_objects:
			dictionary_player_objects[node.player_id] = node
		#Assigns the data to the player object based on the save data
		for player in save_data["Player Info"]:
			var player_id = player["Player ID"]
			if player_id in dictionary_player_objects:
				var current_player = dictionary_player_objects[player["Player ID"]]
				#Tells the current player that it is being loaded in
				current_player.is_loading = true
				current_player.active = bool(player["Active"])
				#If the player is active, emit its state (only emitted once as if it is not the active player it doesn't act on the signal)
				if current_player.active == true:
					autoload_script_signal_manager.player_camera_bind.emit(player["Player Camera State"])
					autoload_script_signal_manager.player_movement.emit(player["Player Movement State"])
				#Breaks down the JSON input into an array of floats and then assigns those floats to the appropriate spots
				#Player Location: A Vector3 of the player location
				#Player Rotation: The rotation of the player body from left to right (the player doesn't look left and right through the camera, it is a full body rotation)
				#Player Camera X Rotation: The up and down of the camera
				var player_saved_position = regex_string_to_array(player["Player Location"])
				current_player.global_position = Vector3(player_saved_position[0], player_saved_position[1], player_saved_position[2])
				current_player.rotation.y = float(player["Player Rotation"])
				current_player.player_head.rotation.x = float(player["Player Camera X Rotation"])
				#Checks the player crouching state, and if crouched, make them crouched
				if player["Player Crouching State"] == true:
					current_player.crouching_state = true
					current_player.force_crouch()
				#Tells the player that it is finished loading
				current_player.is_loading = false
	#endregion Player Managment
	
	#Loads the dialogue into the game
	#region Dialogue Managment
	if save_data["Dialogue Info"].is_empty() != true:
		#There should only ever be one, so we can reference it directly like this (may be changed in the future)
		var dialogue_save_data = save_data["Dialogue Info"][0]
		if dialogue_save_data["Currently Talking"] == true:
			print("TEST TEST TEST WORKING")
			autoload_script_signal_manager.emit_signal("dialogue_object_id", dialogue_save_data["Object ID"])
			autoload_script_signal_manager.emit_signal("dialogue_segment_id", dialogue_save_data["Dialogue Segment"], dialogue_save_data["Dialogue Segment Index"])
			autoload_script_signal_manager.emit_signal("start_dialogue_display", dialogue_save_data["Dialogue Segment Index"])
		else:
			autoload_script_scene_manager.scene_remove("scene_dialogue_ui")
	#endregion Dialogue Managment
#endregion Load Game Functionality


#region Helper Functions
## This function takes in a provided string and extracts the floats from it, returning them in an array
#NOTE This used to be used more, but some changes to loading means that it is no longer used as much
#I am going to leave it here in case I need to use it again in the future. 
func regex_string_to_array(text: String) -> Array:
	var floats = []
	for match in regex.search_all(text):
		floats.append(float(match.get_string()))
	return floats
#endregion Helper Functions
